# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db86280c73cf41a70be1dee0491ab95b9ee8a78fee88358d137838cb7957845cbe3c0a4a5bf07d7d27cd3f0d1d5f6e2e27a1d5075bfbb23551bbaeb7592c75b

test:
  secret_key_base: fcdd25fd53571dbf23364f3c8cbe74b2e3d400593e2f1fc149ec88e4d7ba383054162f64c16ec06df56d9d61477f4b3c14e42dbd7d15ad0d71235da013dda3fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
